import "./globals.css";
import Footer from "@/app/components/Footer";
import Provider from "./context/Provider";
import Navbar from "@/app/components/Navbar";
import { Suspense } from "react";
import Loading from "./loading";
import { JetBrains_Mono } from "next/font/google";
import { Lexend } from "next/font/google";

const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains",
});

const lexend = Lexend({
  subsets: ["latin"],
  variable: "--font-lexend",
});

export const metadata = {
  title: "Peter Shaan",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/avatar.png",
        href: "/avatar.png",
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${jetbrains.variable} font-jetbrains bg-white flex flex-col items-center justify-center  dark:bg-[#111215]`}
      >
        <Provider>
          <Navbar />
          <Suspense fallback={<Loading />}>{children}</Suspense>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
