import "./globals.css";
import Footer from "@/app/components/Footer";
import Provider from "./context/Provider";
import Navbar from "@/app/components/Navbar";
import { Suspense } from "react";
import Loading from "./loading";
import { Inter } from "next/font/google";
import NotifNew from "./components/NotifNew";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Peter Shaan",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/avatar.png",
        href: "/avatar.png",
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable}  bg-white flex flex-col items-center justify-center  dark:bg-[#111215]`}
      >
        <Provider>
          <Navbar />
          {/* Munculin ini selalu saat refresh karena  */}
          <Suspense fallback={<Loading />}>{children}</Suspense>
          <Footer />
          <NotifNew />
        </Provider>
      </body>
    </html>
  );
}
