import "./globals.css";
import Footer from "@/app/components/Footer";
import Provider from "./Provider";
import Navbar from "@/app/components/Navbar";

export const metadata = {
  title: "Peter Shaan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/avatar.png" type="image" sizes="<generated>" />
      <body className="overflow-x-hidden bg-white flex flex-col items-center justify-center  dark:bg-gray-900">
        <Provider>
          <Navbar />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
